import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        void: '#000000',
        'void-soft': '#0a0a0a',
        'void-mid': '#0f0f0f',
        'void-lift': '#141414',
        'void-border': '#1a1a1a',
        'void-muted': '#242424',
        ash: '#888888',
        'ash-dark': '#555555',
        'ash-light': '#aaaaaa',
        ghost: '#cccccc',
        'ghost-bright': '#e8e8e8',
        snow: '#f0f0f0',
        white: '#ffffff',
        blood: '#8b0000',
        'blood-light': '#a30000',
        'blood-bright': '#cc0000',
        'blood-glow': 'rgba(139, 0, 0, 0.15)',
        'blood-glow-strong': 'rgba(139, 0, 0, 0.3)',
      },
      fontFamily: {
        display: ['var(--font-display)', 'Impact', 'Arial Black', 'sans-serif'],
        body: ['var(--font-body)', 'Georgia', 'serif'],
        mono: ['var(--font-mono)', 'Courier New', 'monospace'],
        ui: ['var(--font-ui)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        '2xs': ['0.65rem', { lineHeight: '1rem' }],
        xs: ['0.75rem', { lineHeight: '1.125rem' }],
        sm: ['0.875rem', { lineHeight: '1.375rem' }],
        base: ['1rem', { lineHeight: '1.625rem' }],
        lg: ['1.125rem', { lineHeight: '1.75rem' }],
        xl: ['1.25rem', { lineHeight: '1.875rem' }],
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1.1' }],
        '6xl': ['3.75rem', { lineHeight: '1' }],
        '7xl': ['4.5rem', { lineHeight: '1' }],
        '8xl': ['6rem', { lineHeight: '0.95' }],
        '9xl': ['8rem', { lineHeight: '0.9' }],
        'display': ['clamp(3.5rem, 10vw, 9rem)', { lineHeight: '0.9', letterSpacing: '-0.02em' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '100': '25rem',
        '112': '28rem',
        '128': '32rem',
      },
      maxWidth: {
        'reading': '72ch',
        'wide': '90rem',
      },
      animation: {
        'glitch': 'glitch 4s infinite',
        'flicker': 'flicker 8s infinite',
        'grain': 'grain 0.5s steps(2) infinite',
        'fade-in': 'fadeIn 0.8s ease forwards',
        'slide-up': 'slideUp 0.6s ease forwards',
        'slide-in-right': 'slideInRight 0.5s ease forwards',
        'pulse-red': 'pulseRed 2s ease-in-out infinite',
        'scan': 'scan 6s linear infinite',
        'reveal': 'reveal 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'type': 'type 2s steps(40) forwards',
      },
      keyframes: {
        glitch: {
          '0%, 92%, 100%': { transform: 'translate(0)' },
          '93%': { transform: 'translate(-2px, 1px)', filter: 'hue-rotate(90deg)' },
          '94%': { transform: 'translate(2px, -1px)' },
          '95%': { transform: 'translate(-1px, 2px)', filter: 'hue-rotate(-90deg)' },
          '96%': { transform: 'translate(0)' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '41%': { opacity: '1' },
          '42%': { opacity: '0.8' },
          '43%': { opacity: '1' },
          '45%': { opacity: '0.3' },
          '46%': { opacity: '1' },
        },
        grain: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '10%': { transform: 'translate(-2%, -3%)' },
          '20%': { transform: 'translate(1%, 2%)' },
          '30%': { transform: 'translate(-3%, 1%)' },
          '40%': { transform: 'translate(2%, -2%)' },
          '50%': { transform: 'translate(-1%, 3%)' },
          '60%': { transform: 'translate(3%, 0%)' },
          '70%': { transform: 'translate(0%, -1%)' },
          '80%': { transform: 'translate(-2%, 2%)' },
          '90%': { transform: 'translate(1%, -3%)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(24px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        pulseRed: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(139, 0, 0, 0)' },
          '50%': { boxShadow: '0 0 20px 4px rgba(139, 0, 0, 0.3)' },
        },
        scan: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        reveal: {
          from: { opacity: '0', transform: 'translateY(32px) skewY(2deg)' },
          to: { opacity: '1', transform: 'translateY(0) skewY(0)' },
        },
        type: {
          from: { width: '0' },
          to: { width: '100%' },
        },
      },
      backgroundImage: {
        'noise': "url(\"data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='noise'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23noise)' opacity='0.4'/%3E%3C/svg%3E\")",
        'crt-lines': 'repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.05) 2px, rgba(0,0,0,0.05) 4px)',
        'blood-vignette': 'radial-gradient(ellipse at center, transparent 40%, rgba(139, 0, 0, 0.08) 100%)',
        'dark-vignette': 'radial-gradient(ellipse at center, transparent 50%, rgba(0, 0, 0, 0.7) 100%)',
      },
      boxShadow: {
        'blood': '0 0 30px rgba(139, 0, 0, 0.2)',
        'blood-strong': '0 0 50px rgba(139, 0, 0, 0.4)',
        'blood-inset': 'inset 0 0 30px rgba(139, 0, 0, 0.1)',
        'void': '0 20px 60px rgba(0, 0, 0, 0.8)',
        'card': '0 1px 0 rgba(255,255,255,0.03), 0 4px 20px rgba(0,0,0,0.5)',
        'card-hover': '0 1px 0 rgba(255,255,255,0.05), 0 8px 40px rgba(0,0,0,0.7), 0 0 0 1px rgba(139, 0, 0, 0.2)',
      },
      borderColor: {
        'subtle': '#1a1a1a',
        'muted': '#242424',
        'ghost': '#333333',
      },
      transitionTimingFunction: {
        'expo-out': 'cubic-bezier(0.16, 1, 0.3, 1)',
        'quart-out': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'back-out': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}

export default config
